site_name: TimVink.nl

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: light blue
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light blue
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

hooks:
  - scripts/mkdocs_hooks.py

watch:
  - overrides/

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX

site_url: https://timvink.nl

plugins:
  - search
  - blog:
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
  - social
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

nav:
  - Homepage: index.md
  - Blog:
    - blog/index.md 
  - about.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/extra.css