site_name: TimVink.nl
site_url: https://timvink.nl
site_description: Personal site and blog of Tim Vink
site_author: Tim Vink

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  icon:
      logo: material/bird
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: light blue
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: light blue
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

hooks:
  - scripts/mkdocs_hooks.py

watch:
  - overrides/

extra:
  analytics:
    provider: google
    property: G-343493717
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!

plugins:
  - search
  - blog:
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
  - social
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - redirects:
      redirect_maps:
        'google-cloud-functions.md': 'blog/posts/2019-01-11-google-cloud-functions.md'
        'closest-coordinates.md' : 'blog/posts/2019-02-18-closest-coordinates.md'
        'central-limit-theorem.md' : 'blog/posts/2019-05-16-central-limit-theorem.md'
        'streamlit-threshold-app.md' : 'blog/posts/2020-07-17-streamlit-threshold-app.md'
        'mkdocs-for-tech-doc.md' : 'blog/posts/2020-09-15-mkdocs-for-tech-doc.md'
        'introducing-skorecard.md' : 'blog/posts/2021-12-24-introducing-skorecard.md'
        'reproducible-reports-with-mkdocs.md' : 'blog/posts/2022-01-05-reproducible-reports-with-mkdocs.md'
        'post-balanced-trees.md' : 'blog/posts/2022-06-15-post-balanced-trees.md'
        'is-xgboost-all-we-need.md' : 'blog/posts/2022-09-19-is-xgboost-all-we-need.md'
        'databricks-query-speed.md' : 'blog/posts/2022-12-18-databricks-query-speed.md'

nav:
  - Homepage: index.md
  - Blog:
    - blog/index.md 
  - about.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/extra.css
